apiVersion: v1
kind: Service
metadata:
  name: identityiq
  labels:
    app: identityiq
spec:
  type: NodePort
  selector:
    app: identityiq
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080  # Optional: you can omit this to let Kubernetes choose

